### ISSUE TITLE
NLog removed packages >= 5.0.0-betaXX from NuGet

### ISSUE THREAD

**Issue by jannicklange** [AkkaNetContrib/Akka.Logger.NLog#29]
NLog 5.0.0-XX was removed from NuGet, as it was "Nlog 5 is working, but it's not good enough".
See https://github.com/NLog/NLog/issues/2457

I created a PR that targets NLog 4.5.0-rc06:
https://github.com/AkkaNetContrib/Akka.Logger.NLog/pull/28

It'd be appreciated if you could release a new version of Akka.Logger.NLog soon, since I'd really like to keep using it in my project :)

**Comment by jannicklange** [comment]
Small correction: NLog did not delete the 5.x package, but only unlisted it.
It turns out that it can still be downloaded if you query nuget with the exact version number (which is what happens when the package manager is installing it as a dependency).
I'm not sure why this did not work the first time that I tried to install my nupkg (that uses Akka.Logger.NLog) the first time.

I suppose the downgrade to 4.5 is still somewhat useful, since, currently, NLog 5.0 is dead.

**Comment by Danthar** [comment]
Fixed via #28
