### ISSUE TITLE
EventProperties Layout Renderer

### ISSUE THREAD

**Issue by nsanitate** [AkkaNetContrib/Akka.Logger.NLog#41]
Is it possible to add some custom NLog EventProperties with NLog Akka.NET plugin?

**Comment by snakefoot** [comment]
It should be possible with Akka.Logger.NLog ver. 1.3.3 to use structured logging:

https://github.com/NLog/NLog/wiki/How-to-use-structured-logging

Or you can use `NLog.MappedDiagnosticsLogicalContext.SetScoped` directly and provide properties that can be accessed with https://github.com/NLog/NLog/wiki/MDLC-Layout-Renderer

**Comment by nsanitate** [comment]
It works.
Thank you!

**Comment by nsanitate** [comment]
It works.
Thank you!
